//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullsAndCows.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BullsAndCowsEntities : DbContext
    {
        public BullsAndCowsEntities()
            : base("name=BullsAndCowsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Game> Games { get; set; }
        public DbSet<GameStatus> GameStatuses { get; set; }
        public DbSet<Guess> Guesses { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageState> MessageStates { get; set; }
        public DbSet<MessageType> MessageTypes { get; set; }
        public DbSet<Score> Scores { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
