//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullsAndCows.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.GamesJoined = new HashSet<Game>();
            this.GamesCreated = new HashSet<Game>();
            this.Guesses = new HashSet<Guess>();
            this.Messages = new HashSet<Message>();
            this.Scores = new HashSet<Score>();
        }
    
        public long Id { get; set; }
        public string Username { get; set; }
        public string Nickname { get; set; }
        public string AuthCode { get; set; }
        public string SessionKey { get; set; }
    
        public virtual ICollection<Game> GamesJoined { get; set; }
        public virtual ICollection<Game> GamesCreated { get; set; }
        public virtual ICollection<Guess> Guesses { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
    }
}
