// <auto-generated />
namespace ATMDatabase.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bla));
        
        string IMigrationMetadata.Id
        {
            get { return "201307201651430_bla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
