// <auto-generated />
namespace CodeJewels.DataLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class lala : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lala));
        
        string IMigrationMetadata.Id
        {
            get { return "201308172006346_lala"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
