//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleGame.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Units = new HashSet<Unit>();
            this.UserMessages = new HashSet<UserMessage>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Password { get; set; }
        public long RedUserId { get; set; }
        public Nullable<long> BlueUserId { get; set; }
        public long StatusId { get; set; }
        public Nullable<long> UserInTurn { get; set; }
        public long Turn { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User BlueUser { get; set; }
        public virtual User RedUser { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
        public virtual ICollection<UserMessage> UserMessages { get; set; }
    }
}
