//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleGame.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public long Id { get; set; }
        public decimal Value { get; set; }
        public long UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
