//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleGame.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public long UserId { get; set; }
        public long StateId { get; set; }
        public long TypeId { get; set; }
        public long GameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual MessageState MessageState { get; set; }
        public virtual UserMessagesType UserMessagesType { get; set; }
        public virtual User User { get; set; }
    }
}
