//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleGame.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.GamesJoined = new HashSet<Game>();
            this.GamesCreated = new HashSet<Game>();
            this.Scores = new HashSet<Score>();
            this.Units = new HashSet<Unit>();
            this.UserMessages = new HashSet<UserMessage>();
        }
    
        public long Id { get; set; }
        public string Username { get; set; }
        public string Nickname { get; set; }
        public string AuthCode { get; set; }
        public string SessionKey { get; set; }
    
        public virtual ICollection<Game> GamesJoined { get; set; }
        public virtual ICollection<Game> GamesCreated { get; set; }
        public virtual ICollection<Score> Scores { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
        public virtual ICollection<UserMessage> UserMessages { get; set; }
    }
}
