// <auto-generated />
namespace LibrarySystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class No_Discriminator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(No_Discriminator));
        
        string IMigrationMetadata.Id
        {
            get { return "201309261428375_No_Discriminator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
